services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
